-- Test match for AlgorithmX
-- This match is designed to pass AlgorithmX conditions and return bet=true.

DELETE FROM `matches` WHERE `evid` = 'TEST_ALGX_001';

INSERT INTO `matches` (
    `evid`,
    `sgi`,
    `start_time`,
    `time`,
    `match_status`,
    `country`,
    `liga`,
    `home`,
    `away`,
    `live_ht_hscore`,
    `live_ht_ascore`,
    `live_hscore`,
    `live_ascore`,
    `live_danger_att_home`,
    `live_danger_att_away`,
    `live_shots_on_target_home`,
    `live_shots_on_target_away`,
    `live_shots_off_target_home`,
    `live_shots_off_target_away`,
    `live_corner_home`,
    `live_corner_away`,
    `live_xg_home`,
    `live_xg_away`,
    `live_yellow_cards_home`,
    `live_yellow_cards_away`,
    `live_trend_has_data`,
    `live_trend_window_seconds`,
    `live_trend_shots_total_delta`,
    `live_trend_shots_on_target_delta`,
    `live_trend_danger_attacks_delta`,
    `live_trend_xg_delta`,
    `stats_fetch_status`,
    `stats_updated_at`,
    `live_updated_at`,
    `created_at`,
    `updated_at`
) VALUES (
    'TEST_ALGX_001',
    'TEST_ALGX_SGI_001',
    DATE_SUB(NOW(), INTERVAL 14 MINUTE),
    '14:00',
    'In Play',
    'Testland',
    'AlgorithmX Premier',
    'Pressure United',
    'Rapid City',
    0,
    0,
    0,
    0,
    40,
    35,
    10,
    8,
    12,
    10,
    7,
    6,
    1.45,
    1.18,
    1,
    1,
    1,
    300,
    8,
    5,
    14,
    0.72,
    'success',
    NOW(),
    NOW(),
    NOW(),
    NOW()
);

SELECT
    `id`,
    `evid`,
    `home`,
    `away`,
    `time`,
    `match_status`,
    CONCAT(`live_ht_hscore`, ':', `live_ht_ascore`) AS `score_1h`,
    (`live_danger_att_home` + `live_danger_att_away`) AS `dangerous_attacks_total`,
    (`live_shots_on_target_home` + `live_shots_on_target_away`) AS `shots_on_target_total`,
    (`live_shots_off_target_home` + `live_shots_off_target_away`) AS `shots_off_target_total`,
    (`live_corner_home` + `live_corner_away`) AS `corners_total`
FROM `matches`
WHERE `evid` = 'TEST_ALGX_001';
